---
# tasks/main.yml for newrelic_synthetic_setup
# Configure synthetic monitoring

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - newrelic_synthetic_setup_host is defined
    fail_msg: "newrelic_synthetic_setup_host must be defined"
    quiet: true

- name: Execute newrelic synthetic setup
  ansible.builtin.debug:
    msg: >-
      Configure synthetic monitoring.
      Target: {{ newrelic_synthetic_setup_host }}
