---
# defaults/main.yml for newrelic_workload_setup

# Target host
newrelic_workload_setup_host: ""

# Authentication
newrelic_workload_setup_username: ""
newrelic_workload_setup_password: ""
newrelic_workload_setup_api_key: ""

# Behavior
newrelic_workload_setup_validate_certs: true
newrelic_workload_setup_state: present
