---
# tasks/main.yml for newrelic_workload_setup
# Define and configure workloads

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - newrelic_workload_setup_host is defined
    fail_msg: "newrelic_workload_setup_host must be defined"
    quiet: true

- name: Execute newrelic workload setup
  ansible.builtin.debug:
    msg: >-
      Define and configure workloads.
      Target: {{ newrelic_workload_setup_host }}
