---
# defaults/main.yml for newrelic_agent_deploy

# Target host
newrelic_agent_deploy_host: ""

# Authentication
newrelic_agent_deploy_username: ""
newrelic_agent_deploy_password: ""
newrelic_agent_deploy_api_key: ""

# Behavior
newrelic_agent_deploy_validate_certs: true
newrelic_agent_deploy_state: present
