---
# defaults/main.yml for newrelic_apm_setup

# Target host
newrelic_apm_setup_host: ""

# Authentication
newrelic_apm_setup_username: ""
newrelic_apm_setup_password: ""
newrelic_apm_setup_api_key: ""

# Behavior
newrelic_apm_setup_validate_certs: true
newrelic_apm_setup_state: present
