---
# defaults/main.yml for newrelic_log_management

# Target host
newrelic_log_management_host: ""

# Authentication
newrelic_log_management_username: ""
newrelic_log_management_password: ""
newrelic_log_management_api_key: ""

# Behavior
newrelic_log_management_validate_certs: true
newrelic_log_management_state: present
