---
# defaults/main.yml for newrelic_sli_setup

# Target host
newrelic_sli_setup_host: ""

# Authentication
newrelic_sli_setup_username: ""
newrelic_sli_setup_password: ""
newrelic_sli_setup_api_key: ""

# Behavior
newrelic_sli_setup_validate_certs: true
newrelic_sli_setup_state: present
